### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by npleader** [califano-lab/OncoSig#1]
When trying to install OncoSig, the following errors occurred:

Error : (converted from warning) /private/var/folders/5f/6grfkysd37z9pgz_j398ndz40000gn/T/RtmpARBDXt/R.INSTALLee123df89421/OncoSig/man/OncoSigRF.Rd:88: unexpected section header '\keyword'
ERROR: installing Rd objects failed for package ‘OncoSig’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/OncoSig’
Error: Failed to install 'OncoSig' from GitHub:
  (converted from warning) installation of package ‘/var/folders/5f/6grfkysd37z9pgz_j398ndz40000gn/T//RtmpaIxDwB/fileed616aae39af/OncoSig_0.1.tar.gz’ had non-zero exit status

**Comment by JoshB29** [comment]
We believe this issue was fixed now with [this](https://github.com/califano-lab/OncoSig/commit/ea72260d76d39db6d6b4f12099f163b5fe765cc1) pull request. I am closing this issue, but please feel free to reopen or create a new issue if this/other errors persist.
